---
MANAGEMENT_NETWORK_NAME: mng

ES_DOCKER_IMAGE:  docker.elastic.co/elasticsearch/elasticsearch
ES_DOCKER_IMAGE_TAG: 7.3.2
ES_NETWORK_NAME: elk
ES_SERVICE_NAME: es
ES_CLUSTER_NAME: es-3dm1i-cluster
ES_VOLUME_PATH: /data
ES_JAVA_OPTS: -Xms4g -Xmx4g
ES_DATA_NODE_JAVA_OPTS: -Xms4g -Xmx4g
ES_NO_DATA_NODE_JAVA_OPTS: -Xms2g -Xmx2g

KIBANA_DOCKER_IMAGE: docker.elastic.co/kibana/kibana
KIBANA_PROXY_PORT: 5602

LOGSTASH_DOCKER_IMAGE: docker.elastic.co/logstash/logstash
LOGSTASH_SYSLOG_INPUT_PORT: 1514

CEREBRO_DOCKER_IMAGE:  yannart/cerebro
CEREBRO_DOCKER_IMAGE_TAG: 0.8.1
CEREBRO_PROXY_PORT: 9001

NGINX_USER: admin
NGINX_PASSWORD: admin
NGINX_DOCKER_IMAGE_TAG: 1.17-alpine