
- name: Ensure vm.max is set in /etc/sysctl.conf
  sysctl:
    name: vm.max_map_count
    value: "{{ VM_MAX_MAP_COUNT }}"
    reload: yes

- command: sysctl -p

- name: Create path to map data volumes
  file:
    path: "{{ ES_VOLUME_PATH }}/{{ ES_CLUSTER_NAME }}/{{ ES_SERVICE_NAME }}{{item}}/data"
    state: directory
  # with_sequence: "start=1 end={{ ansible_play_hosts | length }}"
  with_sequence: "start=1 end=4"

- name: Asure mapped volumes ownership to 1000:1000
  file: 
    dest: "{{ ES_VOLUME_PATH }}"
    owner: 1000 
    group: 1000 
    mode: g+rwx 
    recurse: yes
  