- name: Load variables per targer deployment type
  include_vars: "elasticsearch-{{ deployment }}-cluster.yml"
  tags:
     - always

- name: Ensure ES Docker requierments are met
  include: elastic_prerequisites.yml
  tags:
    - always

- name: Spin ES cluster
  include: deploy_elk_cluster.yml
  when: "inventory_hostname == groups['managers'][0]"
